name: HF Space Keep Alive

on:
  schedule:
    - cron: '*/20 * * * *' # Every 20 minutes
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping HF Space
        run: |
          curl -L --fail https://mockingjay-7-neurogan-backend.hf.space/health