name: HF Space Keep Alive
on:
  schedule:
    - cron: '*/20 * * * *' # Pings every 20 minutes
  workflow_dispatch:
2. Jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Pinging HF Space
        run: |
          curl -I https://mockingjay-7-neurogan-backend.hf.space
